### ISSUE TITLE
Dark variant icon theme broken with QGnomePlatform

### ISSUE THREAD

**Issue by tim77** [crow-translate/crow-translate#427]
**Bug description**
Light theme variant works correctly with QGnomePlatform, but broken with dark variant:

**Expected behavior**
It would be great if dark variant theme works correctly as well on non-KDE environments.

**Screenshots**
![Снимок экрана от 2022-05-13 09-10-29](https://user-images.githubusercontent.com/5614476/168242603-40adf83f-001a-4453-8871-97919e885ef4.png)
![Снимок экрана от 2022-05-13 09-10-41](https://user-images.githubusercontent.com/5614476/168242556-fd9d4d69-131d-438d-8677-0d467e928585.png)

**Environment**

- OS: Fedora 36
- Desktop environment: GNOME v42
- Crow Translate version: 2.9.6

**Additional context**
This is continuation of https://github.com/crow-translate/crow-translate/issues/330.

**Comment by Shatur** [comment]
Thanks, definitely should be fixed. But I need help here, not sure how to automatically fallback into the correct theme.

**Comment by gasinvein** [comment]
FWIF, it selects light-theme icons with dark style variant even when the host icon pack has all required icons, e.g. with Papirus. So I guess this problem is not directly related to the bundled icon theme. Maybe it has something to do with the custom `index.theme`? Did it work properly before it?

**Comment by Shatur** [comment]
> FWIW, it selects light-theme icons with dark style variant even when the host icon pack has all required icons, e.g. with Papirus.

No, works correctly with KDE and Papirus for me.

**Comment by evakhoni** [comment]
I confirm the issue still present
Fedora Linux 37
Gnome 43.3
Crow 2.10.3
